### PR TITLE
Avoid blocking for subprocess using @PlatformIO --force option; added @clean command

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ivankravets** [comment]
Should we use `atom.project.getPath()` for https://github.com/vigetlabs/platomformio/blame/master/lib/platomformio-view.coffee#L56 ?

**Comment by ivankravets** [comment]
@vigetlabs thanks a lot for your efforts! :+1:

**Comment by efatsi** [comment]
Looks great, thanks for the PR :+1:

**Comment by efatsi** [comment]
I'll look into cleaning up the directory lookup and push a new version.

**Comment by ivankravets** [comment]
> and push a new version.

Please wait with the new version. I have a few changes. Give me a few minutes.

**Pull request merged**
