### PR TITLE
Update PlatformIO commands according 2.3 release

### PR DESCRIPTION
**Pull request by ivankravets**
Please push this release to Atom Registry. 

Thanks in advance!

### CODE REVIEW

**Comment by ivankravets** [comment]
@efatsi could you merge this pull and release it?

Thanks in advance!

**Comment by efatsi** [comment]
Sorry @ivankravets didn't see this when it came in. Will this push work with older versions of Platformio?

**Comment by ivankravets** [comment]
It will work with PlatformIO >= 2.3, current version is 2.3.2.

**Comment by ivankravets** [comment]
Thanks!

**Comment by efatsi** [comment]
Added you as a collaborator for this project.

**Comment by ivankravets** [comment]
Thank again!

Does Atom Package Registry automatically handle GitHub releases? Which steps should I perform to push new release?

**Comment by efatsi** [comment]
Yeah the command is `apm publish [version]`. That updates the `package.json` file, pushes to github, and deploys to the atom package repository. So don't update `package.json` in your working commits.

**Comment by ivankravets** [comment]
I'll ask you to publish release if it available :smile: :beer:

**Pull request merged**
